const $=s=>document.querySelector(s);
const formInfo=[
['Comunicado','Solicitud de comunicado','Comparte información con los equipos de Inter-Con.','Comunicación interna','VwqabqknjkO3XVMNtDoW2yIdKNcZfitDqs3elECKIT5UMVFLMlFJNzBGNlFRTUMyMkNORjdPNzMzWS4u','<path d="M4 10h5l10-5v14L9 14H4zM9 14l2 7M22 9v6"/>'],
['Diseño','Solicitud de diseño','Solicita materiales digitales o impresos para tu área.','Octubre 2026','VwqabqknjkO3XVMNtDoW2yfu8DrTW4hNn7UwAQ82XgBUMU1SRk5RM0Y5TkowT01QM1NSQ0gySUVaUy4u','<path d="m4 17 13-13 4 4L8 21H4zM14 7l4 4M4 21h17"/>'],
['Campaña','Campaña de reclutamiento','Solicita una campaña para apoyar la cobertura de vacantes.','Octubre 2026','VwqabqknjkO3XVMNtDoW28hjhquOpzhGmljFLZsdhQxUOEQyUk9ORFg1TjZSVzJSRlBCM1UxOVAxSS4u','<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><path d="M12 9v6M9 12h6"/>'],
['Reporte','Efectividad de campañas','Reporta los resultados de campañas de Facebook Reclutamiento.','Octubre 2026','VwqabqknjkO3XVMNtDoW28hjhquOpzhGmljFLZsdhQxUMEpIR0xVWjJUNENKWjhHN05LTFdDS1NTTS4u','<path d="M4 3v18h17M8 17v-5M13 17V8M18 17V5"/>']];
$('#formCards').innerHTML=formInfo.map((f,i)=>`<article class="card"><div class="card-top"><span class="icon"><svg viewBox="0 0 24 24" aria-hidden="true">${f[5]}</svg></span><span class="card-meta">0${i+1} / ${f[3]}</span></div><h2>${f[1]}</h2><p>${f[2]}</p><button type="button" class="card-native" data-view="${['comunicado','diseno','campana','reporte'][i]}">${['Crear comunicado','Crear solicitud','Crear campaña','Ver avance del reporte'][i]}</button></article>`).join('');
const seed=[
{title:'Aviso de actualización de políticas',type:'Comunicado',owner:'Comunicación',date:'2026-10-06',status:'Pendiente',person:'Solicitante de Calidad',area:'Calidad',brief:'Preparar un comunicado interno sobre la actualización de políticas. Incluir un mensaje breve y la fecha de entrada en vigor.',format:'Correo interno'},
{title:'Material para jornada de reclutamiento',type:'Diseño',owner:'Diseño',date:'2026-10-08',status:'En proceso',person:'Solicitante de Recursos Humanos',area:'Recursos Humanos',brief:'Diseñar una pieza digital para difundir la jornada de reclutamiento. Presentar la ubicación, horario y documentos requeridos.',format:'Digital · vertical'},
{title:'Campaña de cobertura operativa',type:'Campaña',owner:'Reclutamiento',date:'2026-10-09',status:'Pendiente',person:'Solicitante de Operaciones',area:'Operaciones',brief:'Preparar una campaña de Facebook para vacantes operativas. Validar ubicación, perfil y condiciones antes de iniciar.',format:'Facebook Reclutamiento'},
{title:'Resultados de campaña · zona norte',type:'Reporte',owner:'Reclutamiento',date:'2026-10-12',status:'Pendiente',person:'Solicitante de Reclutamiento',area:'Reclutamiento',brief:'Concentrar alcance, contactos recibidos y contrataciones de la campaña de ejemplo para revisar su efectividad.',format:'Reporte de resultados'},
{title:'Bienvenida a nuevos colaboradores',type:'Comunicado',owner:'Comunicación',date:'2026-10-02',status:'Realizado',person:'Solicitante de Capital Humano',area:'Capital Humano',brief:'Preparar un mensaje de bienvenida para los nuevos colaboradores del periodo.',format:'Correo interno'},
{title:'Cartel informativo para instalación',type:'Diseño',owner:'Diseño',date:'2026-10-03',status:'Pendiente',person:'Solicitante de Operaciones',area:'Operaciones',brief:'Preparar un cartel impreso con indicaciones de acceso para la instalación.',format:'Impreso · 30 × 40 cm'},
{title:'Pieza de campaña · ubicación pendiente',type:'Diseño',owner:'Diseño',date:'2026-10-14',status:'Rechazado',person:'Solicitante de Reclutamiento',area:'Reclutamiento',brief:'Crear una pieza para difusión de vacantes. La información enviada está incompleta.',format:'Digital · cuadrado',reason:'Falta confirmar la ubicación y el horario de atención.'},
{title:'Recordatorio de capacitación',type:'Comunicado',owner:'Comunicación',date:'2026-10-16',status:'En proceso',person:'Solicitante de Capacitación',area:'Capacitación',brief:'Difundir el recordatorio de capacitación con fecha, hora y modalidad.',format:'Correo interno'}].map((r,i)=>({...r,id:`MKT-${String(i+1).padStart(3,'0')}`,comments:'',evidence:'',reason:r.reason||''}));
let requests=structuredClone(seed),selected=null,year=2026,month=9;
const today='2026-10-05';const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const overdue=r=>r.date<today&&!['Realizado','Rechazado'].includes(r.status);
const dateText=d=>new Date(d+'T12:00:00').toLocaleDateString('es-MX',{day:'numeric',month:'short'});
const scoped=()=>requests.filter(r=>$('#role').value==='admin'||r.owner===$('#role').value);
function view(name){document.querySelectorAll('.view').forEach(e=>e.hidden=e.id!==name);document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));location.hash=name;if(name==='calendario')renderCalendar();}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>view(b.dataset.view)));
function render(){let list=scoped();$('#roleNote').textContent=$('#role').value==='admin'?'Puede reasignar solicitudes entre los equipos.':'Muestra solo las solicitudes asignadas a este equipo.';const stats=[['Asignadas',list.length],['Por atender',list.filter(r=>!['Realizado','Rechazado'].includes(r.status)).length],['Fuera de fecha',list.filter(overdue).length],['Realizadas',list.filter(r=>r.status==='Realizado').length]];$('#stats').innerHTML=stats.map(([l,n])=>`<div class="stat"><strong>${n}</strong><span>${l}</span></div>`).join('');const term=$('#search').value.toLowerCase();list=list.filter(r=>(!$('#type').value||r.type===$('#type').value)&&(!$('#status').value||r.status===$('#status').value)&&`${r.title} ${r.id} ${r.person}`.toLowerCase().includes(term)).sort((a,b)=>a.date.localeCompare(b.date));$('#count').textContent=`${list.length} solicitudes`;$('#rows').innerHTML=list.length?list.map(r=>`<tr><td><strong>${esc(r.title)}</strong><span class="meta">${r.id} · ${r.type} · ${esc(r.area)}</span></td><td>${r.owner}</td><td class="${overdue(r)?'late':''}">${dateText(r.date)}${overdue(r)?'<span class="meta late">Fuera de fecha</span>':''}</td><td><span class="badge ${r.status.replace(' ','-')}">${r.status}</span></td><td><button data-id="${r.id}" aria-label="Ver ${esc(r.title)}">Ver detalle</button></td></tr>`).join(''):'<tr><td colspan="5">No hay solicitudes con estos filtros.</td></tr>';$('#rows').querySelectorAll('button').forEach(b=>b.onclick=()=>openDetail(b.dataset.id));renderCalendar();}
function openDetail(id){const r=requests.find(x=>x.id===id);if(!r)return;selected=id;$('#folio').textContent=r.id+' · '+r.type+' · DEMO';$('#detailTitle').textContent=r.title;$('#detailBody').innerHTML=`<dl class="detail-data"><div><dt>Solicitante de ejemplo</dt><dd>${esc(r.person)}</dd></div><div><dt>Área</dt><dd>${esc(r.area)}</dd></div><div><dt>Fecha de entrega</dt><dd>${dateText(r.date)} de ${r.date.slice(0,4)}</dd></div><div><dt>Entregable</dt><dd>${esc(r.format)}</dd></div></dl><div class="brief">${esc(r.brief)}</div>${r.communication?communicationDetails(r.communication):''}${r.answers?pairsHTML(r.answers):''}`;$('#assigned').value=r.owner;$('#assigned').disabled=$('#role').value!=='admin';$('#editStatus').value=r.status;$('#comments').value=r.comments;$('#evidence').value=r.evidence;$('#reason').value=r.reason;reasonState();$('#detail').showModal();}
function reasonState(){const reject=$('#editStatus').value==='Rechazado';$('#reasonLabel').hidden=!reject;$('#reason').required=reject;}
$('#editStatus').onchange=reasonState;$('#editForm').onsubmit=e=>{e.preventDefault();if($('#editStatus').value==='Rechazado'&&!$('#reason').value.trim()){$('#reason').setCustomValidity('Escribe un motivo de rechazo.');$('#reason').reportValidity();return;}const r=requests.find(x=>x.id===selected);Object.assign(r,{owner:$('#assigned').value,status:$('#editStatus').value,comments:$('#comments').value.trim(),evidence:$('#evidence').value.trim(),reason:$('#reason').value.trim()});$('#detail').close();render();toast('Cambios guardados en la demo.');};$('#reason').oninput=()=>$('#reason').setCustomValidity('');$('#close').onclick=$('#cancel').onclick=()=>$('#detail').close();
$('#reset').onclick=()=>{requests=structuredClone(seed);$('#search').value='';$('#type').value='';$('#status').value='';render();toast('Se restablecieron los datos de ejemplo.');};let timer;function toast(message){clearTimeout(timer);$('#toast').textContent=message;$('#toast').style.display='block';timer=setTimeout(()=>$('#toast').style.display='none',3500);}
['role','type','status'].forEach(id=>$('#'+id).onchange=render);$('#search').oninput=render;
function renderCalendar(){const first=new Date(year,month,1),offset=(first.getDay()+6)%7,days=new Date(year,month+1,0).getDate(),cells=Math.ceil((offset+days)/7)*7;$('#month').textContent=first.toLocaleDateString('es-MX',{month:'long',year:'numeric'});let html='';for(let i=0;i<cells;i++){const n=i-offset+1,d=new Date(year,month,n),key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,out=n<1||n>days;html+=`<div class="day ${out?'out':''} ${key===today?'today':''}"><span class="date">${d.getDate()}</span>${out?'':scoped().filter(r=>r.date===key).map(r=>`<button class="event ${r.type}" data-id="${r.id}">${esc(r.title)}<br><b>${r.owner}</b></button>`).join('')}</div>`;}$('#calendar').innerHTML=html;$('#calendar').querySelectorAll('button').forEach(b=>b.onclick=()=>openDetail(b.dataset.id));}
function shift(delta){month+=delta;if(month<0){month=11;year--;}if(month>11){month=0;year++;}renderCalendar();}$('#prev').onclick=()=>shift(-1);$('#next').onclick=()=>shift(1);
render();view(['equipo','calendario','comunicado','diseno','campana','reporte'].includes(location.hash.slice(1))?location.hash.slice(1):'solicitar');window.addEventListener('hashchange',()=>{const v=location.hash.slice(1);if(['solicitar','equipo','calendario','comunicado','diseno','campana','reporte'].includes(v))view(v);});

const commAreas=['Atención a personal','ABM','Bienestar','Brigadas','Capacitación Operativa','Calidad','Compras','Control Gubernamental','Desarrollo de negocios','Finanzas','IT','Juridico','Logística','MKT','NOM-035','Nóminas e IMSS','Operaciones','Reclutamiento','Tesorería','Ventas','Seguridad e Higiene','Relaciones Laborales','Salud','RHH','Dirección general'];
$('#commArea').innerHTML+=commAreas.map(a=>'<option>'+esc(a)+'</option>').join('');
let commStep=0;
const commFields=()=>new FormData($('#commForm'));
function communicationPairs(c){return [['Compañía',c.company],['Área',c.area],['Objetivo',c.objective],['Destinatarios',c.audiences.join(', ')+(c.otherAudience?' · '+c.otherAudience:'')],['Idioma / opción original',c.language],['Información',c.information],['Liga / URL',c.links||'Sin enlace'],['Contacto',c.contactName],['Correo electrónico',c.contactEmail],['Teléfono',c.contactPhone]];}
function communicationDetails(c){return '<dl class="comm-review">'+communicationPairs(c).map(([k,v])=>'<div><dt>'+esc(k)+'</dt><dd>'+esc(v)+'</dd></div>').join('')+'</dl>';}
function commData(){const steps=Array.from(document.querySelectorAll('[data-comm-step]'));const disabled=steps.map(s=>s.disabled);steps.forEach(s=>s.disabled=false);const f=commFields();steps.forEach((s,i)=>s.disabled=disabled[i]);return Object.fromEntries(['company','area','title','objective','date','language','information','links','contactName','contactEmail','contactPhone','otherAudience'].map(k=>[k,String(f.get(k)||'').trim()]).concat([['audiences',f.getAll('audience')]]));}
function commCapacity(){const date=$('#commDate').value;const count=requests.filter(r=>r.type==='Comunicado'&&r.date===date&&r.status!=='Rechazado').length;$('#capacity').textContent=date?count+' de 2 emisiones ocupadas en esta fecha · calendario demo.':'Selecciona una fecha para consultar el calendario de ejemplo.';$('#capacity').classList.toggle('field-error',!!date&&count>=2);return count;}
function updateReview(){const c=commData();$('#commReview').innerHTML=[['Título',c.title||'Sin título'],['Fecha de difusión',c.date?dateText(c.date)+' de '+c.date.slice(0,4):'Sin fecha'],...communicationPairs(c)].map(([k,v])=>'<div><dt>'+esc(k)+'</dt><dd>'+esc(v)+'</dd></div>').join('');}
function showCommStep(n){commStep=n;document.querySelectorAll('[data-comm-step]').forEach((f,i)=>{f.hidden=i!==n;f.disabled=i!==n;});document.querySelectorAll('[data-step-label]').forEach((e,i)=>{e.classList.toggle('current',i===n);if(i===n)e.setAttribute('aria-current','step');else e.removeAttribute('aria-current');});$('#commBack').hidden=n===0;$('#commNext').hidden=n===2;$('#commSave').hidden=n!==2;$('#commProgress').textContent='Paso '+(n+1)+' de 3';if(n===2){document.querySelectorAll('[data-comm-step]').forEach(f=>f.disabled=false);updateReview();document.querySelectorAll('[data-comm-step]').forEach((f,i)=>f.disabled=i!==n);}const heading=document.querySelector('[data-comm-step="'+n+'"] legend');heading.tabIndex=-1;heading.focus();}
function validateCommStep(){const fields=document.querySelectorAll('[data-comm-step="'+commStep+'"] input,[data-comm-step="'+commStep+'"] select,[data-comm-step="'+commStep+'"] textarea');for(const f of fields){if(f.required&&f.type!=='radio'&&!f.value.trim()){f.setCustomValidity('Completa este campo.');}else f.setCustomValidity('');if(!f.reportValidity())return false;}if(commStep===1){const count=document.querySelectorAll('input[name="audience"]:checked').length;$('#audienceError').hidden=count>0;if(!count){document.querySelector('input[name="audience"]').focus();return false;}if(commCapacity()>=2){$('#commDate').setCustomValidity('Esta fecha ya tiene dos comunicados de ejemplo. Elige otra.');$('#commDate').reportValidity();return false;}}return true;}
$('#commNext').onclick=()=>{if(validateCommStep())showCommStep(commStep+1);};$('#commBack').onclick=()=>showCommStep(commStep-1);
$('#commOther').onchange=()=>{const on=$('#commOther').checked;$('#otherAudienceLabel').hidden=!on;$('#otherAudience').required=on;if(!on)$('#otherAudience').value='';};
$('#commDate').onchange=()=>{$('#commDate').setCustomValidity('');commCapacity();};
$('#commForm').addEventListener('input',e=>{if(e.target.setCustomValidity)e.target.setCustomValidity('');if(e.target.name==='audience')$('#audienceError').hidden=true;if(commStep===2)updateReview();});
$('#commForm').onsubmit=e=>{e.preventDefault();if(commStep!==2){if(validateCommStep())showCommStep(commStep+1);return;}if(!validateCommStep())return;document.querySelectorAll('[data-comm-step]').forEach(f=>f.disabled=false);const c=commData();if(commCapacity()>=2){showCommStep(1);return;}const r={id:'MKT-DEMO-'+String(requests.length+1).padStart(3,'0'),title:c.title||'Comunicado sin título',type:'Comunicado',owner:'Comunicación',date:c.date,status:'Pendiente',person:c.contactName,area:c.area,brief:c.information,format:'Comunicado · '+c.language,comments:'',reason:'',evidence:'',communication:c};requests.push(r);$('#commForm').hidden=true;$('.steps').hidden=true;$('#commSuccess').hidden=false;$('#commSuccessFolio').textContent=r.id+' · '+r.title;render();toast('Solicitud agregada a la demo de esta visita.');};
$('#anotherComm').onclick=()=>{$('#commForm').reset();$('#commForm').hidden=false;$('.steps').hidden=false;$('#commSuccess').hidden=true;$('#otherAudienceLabel').hidden=true;$('#otherAudience').required=false;$('#audienceError').hidden=true;$('#commForm').querySelectorAll('input,select,textarea').forEach(f=>f.setCustomValidity(''));commCapacity();showCommStep(0);};
showCommStep(0);

// Native forms share a step renderer. Only verified source questions are included.
const designAreas=['Dirección','Desarrollo de Negocios','Recursos Humanos-Reclutamiento','Bienestar (D.O.)','Embajada EUA','Operaciones','Capacitación','Seguridad e Higiene (Calidad)','Atención al Personal','Compras','ABM','Legal','Gubernamental','Finanzas','Nóminas','PID','IC ADMIN','Marketing','Otro'];
const printedFormats=['Prototipado para material publicitario','Microperforado','Vinil para pared','Vinil para ventana','Acrílico','Lona','Placa','Banner','Flyer','Tríptico','Catálogo','Cuadernillo','Pines','Propuesta Económica','Otro'].map(v=>v+(v==='Otro'?' (Depende del requerimiento)':['Catálogo','Cuadernillo'].includes(v)?' (Aprox. 7 días hábiles o más, según extensión)':v==='Pines'?' (Aprox. 7 días hábiles)':' (Aprox. 2 días hábiles)'));
const digitalFormats=['Imagen-Post Individual','Cuadernillo','Catálogo','Carrusel para Redes Sociales','Historia para Redes Sociales','Video','Propuesta Económica','Presentación para cliente','Logo','Otro'].map(v=>v+(v==='Otro'?'':v==='Video'?' (Aprox. 7 a 15 días hábiles)':['Cuadernillo','Catálogo','Presentación para cliente'].includes(v)?' (Aprox. 7 días hábiles)':' (Aprox. 2 días hábiles)'));
const clients=['Polaris','APTIV','Henkel','Home Depot','BRIGGS','Uber','MECANIKA TEK','GRAINGER','ELICARGA','ADIENT','ARABELA','WIPRO','TRUPER','Otra respuesta'];
const field=(key,label,type='text',options=[],required=true,help='',when=null)=>({key,label,type,options,required,help,when});
const designFields=[
 [field('area','Área solicitante','select',designAreas),field('otherArea','Especifica tu área','text',[],true,'',d=>d.area==='Otro'),field('person','Responsable que solicita','text',[],true,'Nombre y apellido.')],
 [field('delivery','Tipo de entregable','select',['Impreso','Digital'],false),field('format','Formato del material','select',[],true,'Los plazos son estimados y dependen de la carga del equipo y de recibir información completa.',d=>!!d.delivery),field('otherFormat','Describe el otro requerimiento','textarea',[],true,'',d=>d.format?.startsWith('Otro')),field('orientation','Orientación del diseño','orientation',['Cuadrado','Vertical','Horizontal'],true,'Elige la forma que mejor se adapte a dónde usarás el material. Los ejemplos son ilustrativos.',d=>!!d.delivery),field('sizeUnknown','No sé las medidas / N/A','checkbox',[],false,'Marketing definirá las medidas según el formato y el uso del material.',d=>d.delivery==='Digital'),field('size','Tamaño (medidas)','text',[],true,'',d=>!!d.delivery),field('publication','Fecha de publicación deseada en redes sociales','date',[],false,'Solo si necesitas publicación en redes.',d=>d.delivery==='Digital'),field('date','Fecha de entrega deseada del diseño','date',[],true,'Sujeta a disponibilidad del área de Marketing.')],
 [field('objective','Intención del material / objetivo de comunicación','textarea',[],true,'¿A quién va dirigido, qué quieres lograr y dónde se usará?'),field('title','Título del diseño'),field('text','Texto a incluir','textarea',[],true,'Incluye toda la información que debe aparecer.'),field('language','Idioma del material','select',['Español','Inglés'],true,'Si necesitas ambos idiomas, crea una solicitud por idioma.'),field('extraLogo','¿Debe incluir otro logotipo además del de Inter-Con?','select',['Sí','No']),field('logos','¿Qué logo o logos debemos incluir?','text',[],true,'',d=>d.extraLogo==='Sí'),field('channel','¿Por dónde vas a compartir el material con tu público?','select',['Correo electrónico','WhatsApp','Teams','Redes Sociales','En físico'],false),field('comments','Comentarios o instrucciones adicionales','textarea',[],true,'Estilo visual, imágenes, dudas o necesidad de una junta. Escribe “No aplica” si no hay detalles adicionales.')]
];
const campaignFields=[
 [field('person','Nombre del reclutador'),field('request','Requieres','select',['Reactivación','Nueva campaña']),field('requested','Fecha de solicitud de campaña','date'),field('date','Fecha de inicio de campaña','date'),field('duration','Duración','select',['2 días','3 días','4 días']),field('end','Fecha de finalización de campaña','date')],
 [field('region','Región de la campaña solicitada','select',['Nor Este','Nor Oeste','Metropolitana','Metropolitana Norte','Bajío - Centro - Sur']),field('city','Ciudad operativa de la campaña'),field('clients','Cliente','checks',clients,true,'Selecciona entre 1 y 3 clientes.'),field('otherClient','Especifica el otro cliente','text',[],true,'',d=>d.clients?.includes('Otra respuesta')),field('reason','Motivo de solicitud de campaña','select',['RIESGO','SOLICITUD DEL CLIENTE','CAMBIO DE PLANTILLA','APERTURA','CONTINGENCIA','MAS DE 1 SEMANA CON LA VACANTE','APOYO','APOYO FORANEO','NUEVO SUELDO','OTROS']),field('headcount','¿Cuántas personas requieres contratar?','number')],
 [field('creative','Requieres imagen o texto para tu campaña','select',['Imagen','Texto','Ambas']),field('text','Si requieres solo texto, colócalo aquí','textarea',[],true,'Si solo requieres imagen, escribe “No aplica”.'),field('vacancy','Información de la vacante','textarea',[],true,'Turno, rol, educación mínima, documentación solicitada, lugar de servicio y beneficios.'),field('salary','Salario de la vacante','text',[],true,'Indica importe y periodo de pago.'),field('benefits','Beneficios adicionales','textarea',[],true,'Escribe “No aplica” si no hay beneficios adicionales.'),field('phone','Teléfono del reclutador','tel'),field('materials','Ejemplo o materiales a considerar','file',[],false,'Hasta 3 archivos, 10 MB cada uno. Documentos, imágenes, video o audio. En esta demo se conserva solo su nombre durante la visita.')]
];
function pairsHTML(pairs){return '<dl class="comm-review">'+pairs.map(([k,v])=>'<div><dt>'+esc(k)+'</dt><dd>'+esc(Array.isArray(v)?v.join(', ')||'Sin especificar':v||'Sin especificar')+'</dd></div>').join('')+'</dl>';}
function controlHTML(f,prefix){const id=prefix+'-'+f.key,req=f.required?' required':'';const help=f.help?'<span class="field-help" id="'+id+'-help">'+esc(f.help)+'</span>':'';const described=f.help?' aria-describedby="'+id+'-help"':'';let c;if(f.type==='orientation')return '<div class="native-field" data-field="'+f.key+'"><span class="field-label" id="'+id+'-label">'+esc(f.label)+' <b aria-hidden="true">*</b></span>'+help+'<div class="orientation-cards" role="radiogroup" aria-labelledby="'+id+'-label"'+described+'>'+f.options.map(o=>{const config={Cuadrado:['square','Publicaciones y piezas con texto e imagen equilibrados.'],Vertical:['portrait','Historias, carteles y contenido pensado para verse en el celular.'],Horizontal:['landscape','Presentaciones, banners y videos para pantallas amplias.']}[o];return '<label class="orientation-option"><input type="radio" name="'+f.key+'" value="'+o+'" required><span class="orientation-preview '+config[0]+'" aria-hidden="true"><span class="sample-art"><i></i><b></b><em></em><em></em></span></span><strong>'+o+'</strong><span class="orientation-description">'+config[1]+'</span></label>';}).join('')+'</div></div>';if(f.type==='checkbox')return '<div class="native-field size-unknown" data-field="'+f.key+'"><label class="size-unknown-choice" for="'+id+'"><input id="'+id+'" name="'+f.key+'" type="checkbox"'+described+'><span>'+esc(f.label)+'</span></label>'+help+'</div>';if(f.type==='select')c='<select id="'+id+'" name="'+f.key+'"'+req+described+'><option value="">Selecciona una opción</option>'+f.options.map(o=>'<option>'+esc(o)+'</option>').join('')+'</select>';else if(f.type==='textarea')c='<textarea rows="4" id="'+id+'" name="'+f.key+'"'+req+described+'></textarea>';else if(f.type==='checks')return '<div class="native-field" data-field="'+f.key+'"><span class="field-label" id="'+id+'-label">'+esc(f.label)+' *</span>'+help+'<div class="audience-grid" role="group" aria-labelledby="'+id+'-label">'+f.options.map(o=>'<label><input type="checkbox" name="'+f.key+'" value="'+esc(o)+'"><span>'+esc(o)+'</span></label>').join('')+'</div><p class="field-error" data-check-error hidden>Selecciona entre 1 y 3 clientes.</p></div>';else c='<input id="'+id+'" name="'+f.key+'" type="'+f.type+'"'+req+described+(f.type==='number'?' min="1" step="1"':f.type==='file'?' multiple accept=".doc,.docx,.xls,.xlsx,.ppt,.pptx,.pdf,image/*,video/*,audio/*"':'')+'>';return '<label class="native-field" data-field="'+f.key+'" for="'+id+'">'+esc(f.label)+(f.required?' <b aria-hidden="true">*</b>':' <span class="optional">Opcional</span>')+c+help+'</label>';}
function nativeForm(prefix,title,subtitle,steps,labels,type,owner){
 const root=$('#'+prefix);let step=0;const data={};
 root.innerHTML='<button type="button" class="back-link" data-return>Volver a solicitudes</button><div class="section-head"><div><p class="eyebrow">'+esc(type.toUpperCase())+'</p><h1>'+title+'</h1><p>'+subtitle+'</p></div></div><div class="demo-banner"><strong>Captura de prueba</strong><span>Sin conexión a base de datos. Tus datos duran durante esta visita; no se envían al equipo ni a Microsoft Forms.</span></div><div class="comm-layout"><div class="comm-main"><ol class="steps" aria-label="Pasos">'+[...labels,'Revisión'].map((l,i)=>'<li data-native-label="'+i+'"><span>'+(i+1)+'</span>'+l+'</li>').join('')+'</ol><form novalidate>'+steps.map((fs,i)=>'<fieldset data-native-step="'+i+'"><legend>'+labels[i]+'</legend>'+fs.map(f=>controlHTML(f,prefix)).join('')+'</fieldset>').join('')+'<fieldset data-native-step="'+steps.length+'"><legend>Revisa tu solicitud</legend><div data-review></div></fieldset><div class="comm-actions"><button type="button" data-back>Anterior</button><span data-progress></span><button type="button" class="primary" data-next>Continuar</button><button type="submit" class="primary" data-save hidden>Guardar solicitud demo</button></div></form><div data-success hidden><p class="eyebrow">SOLICITUD DE EJEMPLO GUARDADA</p><h2>Ya aparece en la bandeja de la demo.</h2><p data-folio></p><p>Se perderá al recargar. No se han enviado datos ni archivos a Marketing.</p><div class="dialog-actions"><button type="button" data-another>Crear otra solicitud</button><button type="button" class="primary" data-inbox>Ver bandeja demo</button></div></div></div><aside class="comm-aside"><p class="eyebrow">ANTES DE SOLICITAR</p><h2>'+ (type==='Diseño'?'Información completa, diseño a tiempo.':'Prepara los datos de la vacante.')+'</h2><p>'+ (type==='Diseño'?'Marketing entrega el diseño. La producción del material se coordina con Compras. Los tiempos son aproximados.':'Confirma fechas, ciudad, clientes y condiciones de contratación antes de solicitar la campaña.')+'</p><hr><strong>Revisa antes de guardar</strong><p>Podrás volver a cualquier paso sin perder lo que capturaste.</p></aside></div>';
 const form=root.querySelector('form'),all=steps.flat();
 function capture(){for(const f of all){const els=Array.from(form.querySelectorAll('[name="'+f.key+'"]'));if(f.type==='checks')data[f.key]=els.filter(e=>e.checked).map(e=>e.value);else if(f.type==='orientation')data[f.key]=els.find(e=>e.checked)?.value||'';else if(f.type==='checkbox')data[f.key]=els[0].checked;else if(f.type==='file')data[f.key]=Array.from(els[0].files).map(f=>({name:f.name,size:f.size}));else data[f.key]=els[0].value.trim();}return data;}
 const visible=f=>!f.when||f.when(data);
 function sync(){capture();if(prefix==='diseno'){if(data.delivery!=='Digital'){form.elements.sizeUnknown.checked=false;data.sizeUnknown=false;}const fmt=form.elements.format,opts=data.delivery==='Impreso'?printedFormats:digitalFormats;const prior=fmt.value;if(fmt.dataset.delivery!==data.delivery){fmt.innerHTML='<option value="">Selecciona una opción</option>'+opts.map(o=>'<option>'+esc(o)+'</option>').join('');fmt.dataset.delivery=data.delivery;fmt.value=opts.includes(prior)?prior:'';data.format=fmt.value;}}for(const f of all){const show=visible(f);const wrap=form.querySelector('[data-field="'+f.key+'"]');wrap.hidden=!show;wrap.querySelectorAll('input,textarea,select').forEach(e=>{e.disabled=!show||Number(wrap.closest('fieldset').dataset.nativeStep)!==step||(prefix==='diseno'&&f.key==='size'&&data.sizeUnknown);});}if(prefix==='diseno'){const size=form.elements.size;size.required=!data.sizeUnknown;form.querySelector('[data-field="size"]>b').hidden=data.sizeUnknown;size.setCustomValidity('');size.placeholder=data.sizeUnknown?'N/A · Marketing definirá las medidas':data.delivery==='Impreso'?'Por ejemplo: 30 × 40 cm':'Por ejemplo: 1080 × 1920 px';let help=form.querySelector('[data-size-help]');if(!help){help=document.createElement('span');help.className='field-help';help.dataset.sizeHelp='';help.id=prefix+'-size-help';size.after(help);size.setAttribute('aria-describedby',help.id);}help.textContent=data.delivery==='Impreso'?'Indica las medidas exactas de impresión en cm.':data.sizeUnknown?'Marketing definirá las medidas. Puedes continuar sin escribir un tamaño.':'Indica el ancho × alto en píxeles o cm. Si no los sabes, marca la casilla N/A.';}}
 function answers(){capture();return all.filter(f=>visible(f)&&f.type!=='checkbox').map(f=>[f.label,prefix==='diseno'&&f.key==='size'&&data.sizeUnknown?'N/A · Marketing definirá las medidas':f.type==='file'?(data[f.key]||[]).map(x=>x.name):data[f.key]]);}
 function show(n){step=n;form.querySelectorAll('fieldset').forEach((f,i)=>{f.hidden=i!==n;});sync();root.querySelectorAll('[data-native-label]').forEach((l,i)=>{l.classList.toggle('current',i===n);if(i===n)l.setAttribute('aria-current','step');else l.removeAttribute('aria-current');});root.querySelector('[data-back]').hidden=n===0;root.querySelector('[data-next]').hidden=n===steps.length;root.querySelector('[data-save]').hidden=n!==steps.length;root.querySelector('[data-progress]').textContent='Paso '+(n+1)+' de '+(steps.length+1);if(n===steps.length)root.querySelector('[data-review]').innerHTML=pairsHTML(answers());const legend=form.querySelector('[data-native-step="'+n+'"] legend');legend.tabIndex=-1;legend.focus();}
 function validate(){sync();for(const f of steps[step]||[]){if(!visible(f)||(prefix==='diseno'&&f.key==='size'&&data.sizeUnknown))continue;const el=form.querySelector('[name="'+f.key+'"]');el.setCustomValidity('');if(f.type==='checks'){const ok=data[f.key].length>=1&&data[f.key].length<=3;form.querySelector('[data-check-error]').hidden=ok;if(!ok){el.focus();return false;}}else if(f.type==='file'){const fs=Array.from(el.files);if(fs.length>3||fs.some(x=>x.size>10*1024*1024))el.setCustomValidity('Selecciona hasta 3 archivos de 10 MB como máximo.');else if(fs.some(x=>!(/\.(docx?|xlsx?|pptx?|pdf|png|jpe?g|gif|webp|bmp|svg|mp4|mov|avi|webm|mkv|mp3|wav|m4a|ogg|aac)$/i.test(x.name))))el.setCustomValidity('Usa documentos, imágenes, video o audio.');}else if(f.type==='orientation'){form.querySelectorAll('[name="'+f.key+'"]').forEach(e=>e.setCustomValidity(''));if(!data[f.key])el.setCustomValidity('Selecciona la orientación del diseño.');}else if(f.required&&!data[f.key])el.setCustomValidity('Completa este campo.');if(prefix==='campana'&&['date','end'].includes(f.key)&&data.date&&data.end&&data.end<data.date)form.elements.end.setCustomValidity('La fecha final debe ser igual o posterior al inicio.');if(!el.reportValidity())return false;}return true;}
 form.addEventListener('input',e=>{e.target.setCustomValidity?.('');sync();});form.addEventListener('change',sync);
 root.querySelector('[data-next]').onclick=()=>{if(validate())show(step+1);};root.querySelector('[data-back]').onclick=()=>show(step-1);
 form.onsubmit=e=>{e.preventDefault();if(step!==steps.length){if(validate())show(step+1);return;}const savedAnswers=answers();const r={id:'MKT-DEMO-'+String(requests.length+1).padStart(3,'0'),title:type==='Diseño'?data.title:'Campaña · '+data.city,type,owner,date:data.date,status:'Pendiente',person:data.person,area:(data.area==='Otro'?data.otherArea:data.area)||data.region,brief:data.objective||data.vacancy,format:data.format||data.creative,comments:'',reason:'',evidence:'',answers:savedAnswers};requests.push(r);form.hidden=true;root.querySelector('.steps').hidden=true;root.querySelector('[data-success]').hidden=false;root.querySelector('[data-folio]').textContent=r.id+' · '+r.title;render();toast('Solicitud agregada a la demo de esta visita.');};
 root.querySelector('[data-another]').onclick=()=>{form.reset();form.querySelectorAll('input,textarea,select').forEach(e=>e.setCustomValidity(''));root.querySelector('[data-check-error]')?.setAttribute('hidden','');form.hidden=false;root.querySelector('.steps').hidden=false;root.querySelector('[data-success]').hidden=true;show(0);};
 root.querySelector('[data-return]').onclick=()=>view('solicitar');root.querySelector('[data-inbox]').onclick=()=>view('equipo');show(0);
}
nativeForm('diseno','Solicitud de diseño','Del objetivo al formato: prepara el brief de tu material.',designFields,['Solicitante','Entrega','Contenido'],'Diseño','Diseño');
nativeForm('campana','Campaña de reclutamiento','Comparte la vacante y el periodo que necesitas cubrir.',campaignFields,['Fechas','Cobertura','Materiales'],'Campaña','Reclutamiento');
$('#reporte').innerHTML='<button type="button" class="back-link" id="reportBack">Volver a solicitudes</button><div class="section-head"><div><p class="eyebrow">EN PREPARACIÓN</p><h1>Efectividad de campañas</h1><p>Un reporte por cada campaña solicitada.</p></div></div><div class="demo-banner"><strong>Faltan preguntas por verificar</strong><span>El Forms exige dos archivos para mostrar las siguientes secciones. Esta captura estará disponible cuando completemos su estructura.</span></div><div class="comm-main report-preview"><h2>Secciones verificadas</h2><h3>Datos generales</h3><ul><li>Nombre del reclutador.</li><li>Fecha del reporte y fecha de campaña solicitada.</li><li>Región y ciudad de la campaña.</li><li>Presupuesto gastado.</li></ul><h3>Evidencias</h3><ul><li>Compilado de conversaciones recibidas, en PDF.</li><li>Evidencia de mensajes con cita a oficinas, en PDF.</li></ul><p>El formulario solicita un archivo por evidencia, de hasta 10 MB. Las preguntas posteriores todavía están pendientes de revisión.</p></div>';
$('#reportBack').onclick=()=>view('solicitar');
