const $=s=>document.querySelector(s);
const formInfo=[
['Comunicado','Solicitud de comunicado','Comparte información con los equipos de Inter-Con.','Comunicación interna','VwqabqknjkO3XVMNtDoW2yIdKNcZfitDqs3elECKIT5UMVFLMlFJNzBGNlFRTUMyMkNORjdPNzMzWS4u','<path d="M4 10h5l10-5v14L9 14H4zM9 14l2 7M22 9v6"/>'],
['Diseño','Solicitud de diseño','Solicita materiales digitales o impresos para tu área.','Octubre 2026','VwqabqknjkO3XVMNtDoW2yfu8DrTW4hNn7UwAQ82XgBUMU1SRk5RM0Y5TkowT01QM1NSQ0gySUVaUy4u','<path d="m4 17 13-13 4 4L8 21H4zM14 7l4 4M4 21h17"/>'],
['Campaña','Campaña de reclutamiento','Solicita una campaña para apoyar la cobertura de vacantes.','Octubre 2026','VwqabqknjkO3XVMNtDoW28hjhquOpzhGmljFLZsdhQxUOEQyUk9ORFg1TjZSVzJSRlBCM1UxOVAxSS4u','<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><path d="M12 9v6M9 12h6"/>'],
['Reporte','Efectividad de campañas','Reporta los resultados de campañas de Facebook Reclutamiento.','Octubre 2026','VwqabqknjkO3XVMNtDoW28hjhquOpzhGmljFLZsdhQxUMEpIR0xVWjJUNENKWjhHN05LTFdDS1NTTS4u','<path d="M4 3v18h17M8 17v-5M13 17V8M18 17V5"/>']];
$('#formCards').innerHTML=formInfo.map((f,i)=>`<article class="card"><div class="card-top"><span class="icon"><svg viewBox="0 0 24 24" aria-hidden="true">${f[5]}</svg></span><span class="card-meta">0${i+1} / ${f[3]}</span></div><h2>${f[1]}</h2><p>${f[2]}</p><a href="https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=${f[4]}${i===3?'&amp;route=shorturl':''}" target="_blank" rel="noopener noreferrer" aria-label="Abrir ${f[1]} en una nueva pestaña">Abrir formulario</a></article>`).join('');
const seed=[
{title:'Aviso de actualización de políticas',type:'Comunicado',owner:'Comunicación',date:'2026-10-06',status:'Pendiente',person:'Solicitante de Calidad',area:'Calidad',brief:'Preparar un comunicado interno sobre la actualización de políticas. Incluir un mensaje breve y la fecha de entrada en vigor.',format:'Correo interno'},
{title:'Material para jornada de reclutamiento',type:'Diseño',owner:'Diseño',date:'2026-10-08',status:'En proceso',person:'Solicitante de Recursos Humanos',area:'Recursos Humanos',brief:'Diseñar una pieza digital para difundir la jornada de reclutamiento. Presentar la ubicación, horario y documentos requeridos.',format:'Digital · vertical'},
{title:'Campaña de cobertura operativa',type:'Campaña',owner:'Reclutamiento',date:'2026-10-09',status:'Pendiente',person:'Solicitante de Operaciones',area:'Operaciones',brief:'Preparar una campaña de Facebook para vacantes operativas. Validar ubicación, perfil y condiciones antes de iniciar.',format:'Facebook Reclutamiento'},
{title:'Resultados de campaña · zona norte',type:'Reporte',owner:'Reclutamiento',date:'2026-10-12',status:'Pendiente',person:'Solicitante de Reclutamiento',area:'Reclutamiento',brief:'Concentrar alcance, contactos recibidos y contrataciones de la campaña de ejemplo para revisar su efectividad.',format:'Reporte de resultados'},
{title:'Bienvenida a nuevos colaboradores',type:'Comunicado',owner:'Comunicación',date:'2026-10-02',status:'Realizado',person:'Solicitante de Capital Humano',area:'Capital Humano',brief:'Preparar un mensaje de bienvenida para los nuevos colaboradores del periodo.',format:'Correo interno'},
{title:'Cartel informativo para instalación',type:'Diseño',owner:'Diseño',date:'2026-10-03',status:'Pendiente',person:'Solicitante de Operaciones',area:'Operaciones',brief:'Preparar un cartel impreso con indicaciones de acceso para la instalación.',format:'Impreso · 30 × 40 cm'},
{title:'Pieza de campaña · ubicación pendiente',type:'Diseño',owner:'Diseño',date:'2026-10-14',status:'Rechazado',person:'Solicitante de Reclutamiento',area:'Reclutamiento',brief:'Crear una pieza para difusión de vacantes. La información enviada está incompleta.',format:'Digital · cuadrado',reason:'Falta confirmar la ubicación y el horario de atención.'},
{title:'Recordatorio de capacitación',type:'Comunicado',owner:'Comunicación',date:'2026-10-16',status:'En proceso',person:'Solicitante de Capacitación',area:'Capacitación',brief:'Difundir el recordatorio de capacitación con fecha, hora y modalidad.',format:'Correo interno'}].map((r,i)=>({...r,id:`MKT-${String(i+1).padStart(3,'0')}`,comments:'',evidence:'',reason:r.reason||''}));
let requests=structuredClone(seed),selected=null,year=2026,month=9;
const today='2026-10-05';const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const overdue=r=>r.date<today&&!['Realizado','Rechazado'].includes(r.status);
const dateText=d=>new Date(d+'T12:00:00').toLocaleDateString('es-MX',{day:'numeric',month:'short'});
const scoped=()=>requests.filter(r=>$('#role').value==='admin'||r.owner===$('#role').value);
function view(name){document.querySelectorAll('.view').forEach(e=>e.hidden=e.id!==name);document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));location.hash=name;if(name==='calendario')renderCalendar();}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>view(b.dataset.view)));
function render(){let list=scoped();$('#roleNote').textContent=$('#role').value==='admin'?'Puede reasignar solicitudes entre los equipos.':'Muestra solo las solicitudes asignadas a este equipo.';const stats=[['Asignadas',list.length],['Por atender',list.filter(r=>!['Realizado','Rechazado'].includes(r.status)).length],['Fuera de fecha',list.filter(overdue).length],['Realizadas',list.filter(r=>r.status==='Realizado').length]];$('#stats').innerHTML=stats.map(([l,n])=>`<div class="stat"><strong>${n}</strong><span>${l}</span></div>`).join('');const term=$('#search').value.toLowerCase();list=list.filter(r=>(!$('#type').value||r.type===$('#type').value)&&(!$('#status').value||r.status===$('#status').value)&&`${r.title} ${r.id} ${r.person}`.toLowerCase().includes(term)).sort((a,b)=>a.date.localeCompare(b.date));$('#count').textContent=`${list.length} solicitudes`;$('#rows').innerHTML=list.length?list.map(r=>`<tr><td><strong>${esc(r.title)}</strong><span class="meta">${r.id} · ${r.type} · ${esc(r.area)}</span></td><td>${r.owner}</td><td class="${overdue(r)?'late':''}">${dateText(r.date)}${overdue(r)?'<span class="meta late">Fuera de fecha</span>':''}</td><td><span class="badge ${r.status.replace(' ','-')}">${r.status}</span></td><td><button data-id="${r.id}" aria-label="Ver ${esc(r.title)}">Ver detalle</button></td></tr>`).join(''):'<tr><td colspan="5">No hay solicitudes con estos filtros.</td></tr>';$('#rows').querySelectorAll('button').forEach(b=>b.onclick=()=>openDetail(b.dataset.id));renderCalendar();}
function openDetail(id){const r=requests.find(x=>x.id===id);if(!r)return;selected=id;$('#folio').textContent=r.id+' · '+r.type+' · DEMO';$('#detailTitle').textContent=r.title;$('#detailBody').innerHTML=`<dl class="detail-data"><div><dt>Solicitante de ejemplo</dt><dd>${esc(r.person)}</dd></div><div><dt>Área</dt><dd>${esc(r.area)}</dd></div><div><dt>Fecha de entrega</dt><dd>${dateText(r.date)} de 2026</dd></div><div><dt>Entregable</dt><dd>${esc(r.format)}</dd></div></dl><div class="brief">${esc(r.brief)}</div>`;$('#assigned').value=r.owner;$('#assigned').disabled=$('#role').value!=='admin';$('#editStatus').value=r.status;$('#comments').value=r.comments;$('#evidence').value=r.evidence;$('#reason').value=r.reason;reasonState();$('#detail').showModal();}
function reasonState(){const reject=$('#editStatus').value==='Rechazado';$('#reasonLabel').hidden=!reject;$('#reason').required=reject;}
$('#editStatus').onchange=reasonState;$('#editForm').onsubmit=e=>{e.preventDefault();if($('#editStatus').value==='Rechazado'&&!$('#reason').value.trim()){$('#reason').setCustomValidity('Escribe un motivo de rechazo.');$('#reason').reportValidity();return;}const r=requests.find(x=>x.id===selected);Object.assign(r,{owner:$('#assigned').value,status:$('#editStatus').value,comments:$('#comments').value.trim(),evidence:$('#evidence').value.trim(),reason:$('#reason').value.trim()});$('#detail').close();render();toast('Cambios guardados en la demo.');};$('#reason').oninput=()=>$('#reason').setCustomValidity('');$('#close').onclick=$('#cancel').onclick=()=>$('#detail').close();
$('#reset').onclick=()=>{requests=structuredClone(seed);$('#search').value='';$('#type').value='';$('#status').value='';render();toast('Se restablecieron los datos de ejemplo.');};let timer;function toast(message){clearTimeout(timer);$('#toast').textContent=message;$('#toast').style.display='block';timer=setTimeout(()=>$('#toast').style.display='none',3500);}
['role','type','status'].forEach(id=>$('#'+id).onchange=render);$('#search').oninput=render;
function renderCalendar(){const first=new Date(year,month,1),offset=(first.getDay()+6)%7,days=new Date(year,month+1,0).getDate(),cells=Math.ceil((offset+days)/7)*7;$('#month').textContent=first.toLocaleDateString('es-MX',{month:'long',year:'numeric'});let html='';for(let i=0;i<cells;i++){const n=i-offset+1,d=new Date(year,month,n),key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,out=n<1||n>days;html+=`<div class="day ${out?'out':''} ${key===today?'today':''}"><span class="date">${d.getDate()}</span>${out?'':scoped().filter(r=>r.date===key).map(r=>`<button class="event ${r.type}" data-id="${r.id}">${esc(r.title)}<br><b>${r.owner}</b></button>`).join('')}</div>`;}$('#calendar').innerHTML=html;$('#calendar').querySelectorAll('button').forEach(b=>b.onclick=()=>openDetail(b.dataset.id));}
function shift(delta){month+=delta;if(month<0){month=11;year--;}if(month>11){month=0;year++;}renderCalendar();}$('#prev').onclick=()=>shift(-1);$('#next').onclick=()=>shift(1);
render();view(['equipo','calendario'].includes(location.hash.slice(1))?location.hash.slice(1):'solicitar');window.addEventListener('hashchange',()=>{const v=location.hash.slice(1);if(['solicitar','equipo','calendario'].includes(v))view(v);});
