const $=s=>document.querySelector(s);
const formInfo=[
['Comunicado','Solicitud de comunicado','Comparte información con los equipos de Inter-Con.','Comunicación interna','VwqabqknjkO3XVMNtDoW2yIdKNcZfitDqs3elECKIT5UMVFLMlFJNzBGNlFRTUMyMkNORjdPNzMzWS4u','<path d="M4 10h5l10-5v14L9 14H4zM9 14l2 7M22 9v6"/>'],
['Diseño','Solicitud de diseño','Solicita materiales digitales o impresos para tu área.','Octubre 2026','VwqabqknjkO3XVMNtDoW2yfu8DrTW4hNn7UwAQ82XgBUMU1SRk5RM0Y5TkowT01QM1NSQ0gySUVaUy4u','<path d="m4 17 13-13 4 4L8 21H4zM14 7l4 4M4 21h17"/>'],
['Campaña','Campaña de reclutamiento','Solicita una campaña para apoyar la cobertura de vacantes.','Octubre 2026','VwqabqknjkO3XVMNtDoW28hjhquOpzhGmljFLZsdhQxUOEQyUk9ORFg1TjZSVzJSRlBCM1UxOVAxSS4u','<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><path d="M12 9v6M9 12h6"/>'],
['Reporte','Efectividad de campañas','Reporta los resultados de campañas de Facebook Reclutamiento.','Octubre 2026','VwqabqknjkO3XVMNtDoW28hjhquOpzhGmljFLZsdhQxUMEpIR0xVWjJUNENKWjhHN05LTFdDS1NTTS4u','<path d="M4 3v18h17M8 17v-5M13 17V8M18 17V5"/>']];
$('#formCards').innerHTML=formInfo.map((f,i)=>`<article class="card"><div class="card-top"><span class="icon"><svg viewBox="0 0 24 24" aria-hidden="true">${f[5]}</svg></span><span class="card-meta">0${i+1} / ${f[3]}</span></div><h2>${f[1]}</h2><p>${f[2]}</p>${i===0?'<button type="button" class="card-native" data-view="comunicado">Crear comunicado</button>':`<a href="https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=${f[4]}${i===3?'&amp;route=shorturl':''}" target="_blank" rel="noopener noreferrer" aria-label="Abrir ${f[1]} en una nueva pestaña">Abrir formulario</a>`}</article>`).join('');
const seed=[
{title:'Aviso de actualización de políticas',type:'Comunicado',owner:'Comunicación',date:'2026-10-06',status:'Pendiente',person:'Solicitante de Calidad',area:'Calidad',brief:'Preparar un comunicado interno sobre la actualización de políticas. Incluir un mensaje breve y la fecha de entrada en vigor.',format:'Correo interno'},
{title:'Material para jornada de reclutamiento',type:'Diseño',owner:'Diseño',date:'2026-10-08',status:'En proceso',person:'Solicitante de Recursos Humanos',area:'Recursos Humanos',brief:'Diseñar una pieza digital para difundir la jornada de reclutamiento. Presentar la ubicación, horario y documentos requeridos.',format:'Digital · vertical'},
{title:'Campaña de cobertura operativa',type:'Campaña',owner:'Reclutamiento',date:'2026-10-09',status:'Pendiente',person:'Solicitante de Operaciones',area:'Operaciones',brief:'Preparar una campaña de Facebook para vacantes operativas. Validar ubicación, perfil y condiciones antes de iniciar.',format:'Facebook Reclutamiento'},
{title:'Resultados de campaña · zona norte',type:'Reporte',owner:'Reclutamiento',date:'2026-10-12',status:'Pendiente',person:'Solicitante de Reclutamiento',area:'Reclutamiento',brief:'Concentrar alcance, contactos recibidos y contrataciones de la campaña de ejemplo para revisar su efectividad.',format:'Reporte de resultados'},
{title:'Bienvenida a nuevos colaboradores',type:'Comunicado',owner:'Comunicación',date:'2026-10-02',status:'Realizado',person:'Solicitante de Capital Humano',area:'Capital Humano',brief:'Preparar un mensaje de bienvenida para los nuevos colaboradores del periodo.',format:'Correo interno'},
{title:'Cartel informativo para instalación',type:'Diseño',owner:'Diseño',date:'2026-10-03',status:'Pendiente',person:'Solicitante de Operaciones',area:'Operaciones',brief:'Preparar un cartel impreso con indicaciones de acceso para la instalación.',format:'Impreso · 30 × 40 cm'},
{title:'Pieza de campaña · ubicación pendiente',type:'Diseño',owner:'Diseño',date:'2026-10-14',status:'Rechazado',person:'Solicitante de Reclutamiento',area:'Reclutamiento',brief:'Crear una pieza para difusión de vacantes. La información enviada está incompleta.',format:'Digital · cuadrado',reason:'Falta confirmar la ubicación y el horario de atención.'},
{title:'Recordatorio de capacitación',type:'Comunicado',owner:'Comunicación',date:'2026-10-16',status:'En proceso',person:'Solicitante de Capacitación',area:'Capacitación',brief:'Difundir el recordatorio de capacitación con fecha, hora y modalidad.',format:'Correo interno'}].map((r,i)=>({...r,id:`MKT-${String(i+1).padStart(3,'0')}`,comments:'',evidence:'',reason:r.reason||''}));
let requests=structuredClone(seed),selected=null,year=2026,month=9;
const today='2026-10-05';const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const overdue=r=>r.date<today&&!['Realizado','Rechazado'].includes(r.status);
const dateText=d=>new Date(d+'T12:00:00').toLocaleDateString('es-MX',{day:'numeric',month:'short'});
const scoped=()=>requests.filter(r=>$('#role').value==='admin'||r.owner===$('#role').value);
function view(name){document.querySelectorAll('.view').forEach(e=>e.hidden=e.id!==name);document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));location.hash=name;if(name==='calendario')renderCalendar();}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>view(b.dataset.view)));
function render(){let list=scoped();$('#roleNote').textContent=$('#role').value==='admin'?'Puede reasignar solicitudes entre los equipos.':'Muestra solo las solicitudes asignadas a este equipo.';const stats=[['Asignadas',list.length],['Por atender',list.filter(r=>!['Realizado','Rechazado'].includes(r.status)).length],['Fuera de fecha',list.filter(overdue).length],['Realizadas',list.filter(r=>r.status==='Realizado').length]];$('#stats').innerHTML=stats.map(([l,n])=>`<div class="stat"><strong>${n}</strong><span>${l}</span></div>`).join('');const term=$('#search').value.toLowerCase();list=list.filter(r=>(!$('#type').value||r.type===$('#type').value)&&(!$('#status').value||r.status===$('#status').value)&&`${r.title} ${r.id} ${r.person}`.toLowerCase().includes(term)).sort((a,b)=>a.date.localeCompare(b.date));$('#count').textContent=`${list.length} solicitudes`;$('#rows').innerHTML=list.length?list.map(r=>`<tr><td><strong>${esc(r.title)}</strong><span class="meta">${r.id} · ${r.type} · ${esc(r.area)}</span></td><td>${r.owner}</td><td class="${overdue(r)?'late':''}">${dateText(r.date)}${overdue(r)?'<span class="meta late">Fuera de fecha</span>':''}</td><td><span class="badge ${r.status.replace(' ','-')}">${r.status}</span></td><td><button data-id="${r.id}" aria-label="Ver ${esc(r.title)}">Ver detalle</button></td></tr>`).join(''):'<tr><td colspan="5">No hay solicitudes con estos filtros.</td></tr>';$('#rows').querySelectorAll('button').forEach(b=>b.onclick=()=>openDetail(b.dataset.id));renderCalendar();}
function openDetail(id){const r=requests.find(x=>x.id===id);if(!r)return;selected=id;$('#folio').textContent=r.id+' · '+r.type+' · DEMO';$('#detailTitle').textContent=r.title;$('#detailBody').innerHTML=`<dl class="detail-data"><div><dt>Solicitante de ejemplo</dt><dd>${esc(r.person)}</dd></div><div><dt>Área</dt><dd>${esc(r.area)}</dd></div><div><dt>Fecha de entrega</dt><dd>${dateText(r.date)} de 2026</dd></div><div><dt>Entregable</dt><dd>${esc(r.format)}</dd></div></dl><div class="brief">${esc(r.brief)}</div>${r.communication?communicationDetails(r.communication):''}`;$('#assigned').value=r.owner;$('#assigned').disabled=$('#role').value!=='admin';$('#editStatus').value=r.status;$('#comments').value=r.comments;$('#evidence').value=r.evidence;$('#reason').value=r.reason;reasonState();$('#detail').showModal();}
function reasonState(){const reject=$('#editStatus').value==='Rechazado';$('#reasonLabel').hidden=!reject;$('#reason').required=reject;}
$('#editStatus').onchange=reasonState;$('#editForm').onsubmit=e=>{e.preventDefault();if($('#editStatus').value==='Rechazado'&&!$('#reason').value.trim()){$('#reason').setCustomValidity('Escribe un motivo de rechazo.');$('#reason').reportValidity();return;}const r=requests.find(x=>x.id===selected);Object.assign(r,{owner:$('#assigned').value,status:$('#editStatus').value,comments:$('#comments').value.trim(),evidence:$('#evidence').value.trim(),reason:$('#reason').value.trim()});$('#detail').close();render();toast('Cambios guardados en la demo.');};$('#reason').oninput=()=>$('#reason').setCustomValidity('');$('#close').onclick=$('#cancel').onclick=()=>$('#detail').close();
$('#reset').onclick=()=>{requests=structuredClone(seed);$('#search').value='';$('#type').value='';$('#status').value='';render();toast('Se restablecieron los datos de ejemplo.');};let timer;function toast(message){clearTimeout(timer);$('#toast').textContent=message;$('#toast').style.display='block';timer=setTimeout(()=>$('#toast').style.display='none',3500);}
['role','type','status'].forEach(id=>$('#'+id).onchange=render);$('#search').oninput=render;
function renderCalendar(){const first=new Date(year,month,1),offset=(first.getDay()+6)%7,days=new Date(year,month+1,0).getDate(),cells=Math.ceil((offset+days)/7)*7;$('#month').textContent=first.toLocaleDateString('es-MX',{month:'long',year:'numeric'});let html='';for(let i=0;i<cells;i++){const n=i-offset+1,d=new Date(year,month,n),key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,out=n<1||n>days;html+=`<div class="day ${out?'out':''} ${key===today?'today':''}"><span class="date">${d.getDate()}</span>${out?'':scoped().filter(r=>r.date===key).map(r=>`<button class="event ${r.type}" data-id="${r.id}">${esc(r.title)}<br><b>${r.owner}</b></button>`).join('')}</div>`;}$('#calendar').innerHTML=html;$('#calendar').querySelectorAll('button').forEach(b=>b.onclick=()=>openDetail(b.dataset.id));}
function shift(delta){month+=delta;if(month<0){month=11;year--;}if(month>11){month=0;year++;}renderCalendar();}$('#prev').onclick=()=>shift(-1);$('#next').onclick=()=>shift(1);
render();view(['equipo','calendario','comunicado'].includes(location.hash.slice(1))?location.hash.slice(1):'solicitar');window.addEventListener('hashchange',()=>{const v=location.hash.slice(1);if(['solicitar','equipo','calendario','comunicado'].includes(v))view(v);});

const commAreas=['Atención a personal','ABM','Bienestar','Brigadas','Capacitación Operativa','Calidad','Compras','Control Gubernamental','Desarrollo de negocios','Finanzas','IT','Juridico','Logística','MKT','NOM-035','Nóminas e IMSS','Operaciones','Reclutamiento','Tesorería','Ventas','Seguridad e Higiene','Relaciones Laborales','Salud','RHH','Dirección general'];
$('#commArea').innerHTML+=commAreas.map(a=>'<option>'+esc(a)+'</option>').join('');
let commStep=0;
const commFields=()=>new FormData($('#commForm'));
function communicationPairs(c){return [['Compañía',c.company],['Área',c.area],['Objetivo',c.objective],['Destinatarios',c.audiences.join(', ')+(c.otherAudience?' · '+c.otherAudience:'')],['Idioma / opción original',c.language],['Información',c.information],['Liga / URL',c.links||'Sin enlace'],['Contacto',c.contactName],['Correo electrónico',c.contactEmail],['Teléfono',c.contactPhone]];}
function communicationDetails(c){return '<dl class="comm-review">'+communicationPairs(c).map(([k,v])=>'<div><dt>'+esc(k)+'</dt><dd>'+esc(v)+'</dd></div>').join('')+'</dl>';}
function commData(){const steps=Array.from(document.querySelectorAll('[data-comm-step]'));const disabled=steps.map(s=>s.disabled);steps.forEach(s=>s.disabled=false);const f=commFields();steps.forEach((s,i)=>s.disabled=disabled[i]);return Object.fromEntries(['company','area','title','objective','date','language','information','links','contactName','contactEmail','contactPhone','otherAudience'].map(k=>[k,String(f.get(k)||'').trim()]).concat([['audiences',f.getAll('audience')]]));}
function commCapacity(){const date=$('#commDate').value;const count=requests.filter(r=>r.type==='Comunicado'&&r.date===date&&r.status!=='Rechazado').length;$('#capacity').textContent=date?count+' de 2 emisiones ocupadas en esta fecha · calendario demo.':'Selecciona una fecha para consultar el calendario de ejemplo.';$('#capacity').classList.toggle('field-error',!!date&&count>=2);return count;}
function updateReview(){const c=commData();$('#commReview').innerHTML=[['Título',c.title||'Sin título'],['Fecha de difusión',c.date?dateText(c.date)+' de '+c.date.slice(0,4):'Sin fecha'],...communicationPairs(c)].map(([k,v])=>'<div><dt>'+esc(k)+'</dt><dd>'+esc(v)+'</dd></div>').join('');}
function showCommStep(n){commStep=n;document.querySelectorAll('[data-comm-step]').forEach((f,i)=>{f.hidden=i!==n;f.disabled=i!==n;});document.querySelectorAll('[data-step-label]').forEach((e,i)=>{e.classList.toggle('current',i===n);if(i===n)e.setAttribute('aria-current','step');else e.removeAttribute('aria-current');});$('#commBack').hidden=n===0;$('#commNext').hidden=n===2;$('#commSave').hidden=n!==2;$('#commProgress').textContent='Paso '+(n+1)+' de 3';if(n===2){document.querySelectorAll('[data-comm-step]').forEach(f=>f.disabled=false);updateReview();document.querySelectorAll('[data-comm-step]').forEach((f,i)=>f.disabled=i!==n);}const heading=document.querySelector('[data-comm-step="'+n+'"] legend');heading.tabIndex=-1;heading.focus();}
function validateCommStep(){const fields=document.querySelectorAll('[data-comm-step="'+commStep+'"] input,[data-comm-step="'+commStep+'"] select,[data-comm-step="'+commStep+'"] textarea');for(const f of fields){if(f.required&&f.type!=='radio'&&!f.value.trim()){f.setCustomValidity('Completa este campo.');}else f.setCustomValidity('');if(!f.reportValidity())return false;}if(commStep===1){const count=document.querySelectorAll('input[name="audience"]:checked').length;$('#audienceError').hidden=count>0;if(!count){document.querySelector('input[name="audience"]').focus();return false;}if(commCapacity()>=2){$('#commDate').setCustomValidity('Esta fecha ya tiene dos comunicados de ejemplo. Elige otra.');$('#commDate').reportValidity();return false;}}return true;}
$('#commNext').onclick=()=>{if(validateCommStep())showCommStep(commStep+1);};$('#commBack').onclick=()=>showCommStep(commStep-1);
$('#commOther').onchange=()=>{const on=$('#commOther').checked;$('#otherAudienceLabel').hidden=!on;$('#otherAudience').required=on;if(!on)$('#otherAudience').value='';};
$('#commDate').onchange=()=>{$('#commDate').setCustomValidity('');commCapacity();};
$('#commForm').addEventListener('input',e=>{if(e.target.setCustomValidity)e.target.setCustomValidity('');if(e.target.name==='audience')$('#audienceError').hidden=true;if(commStep===2)updateReview();});
$('#commForm').onsubmit=e=>{e.preventDefault();if(commStep!==2){if(validateCommStep())showCommStep(commStep+1);return;}if(!validateCommStep())return;document.querySelectorAll('[data-comm-step]').forEach(f=>f.disabled=false);const c=commData();if(commCapacity()>=2){showCommStep(1);return;}const r={id:'MKT-DEMO-'+String(requests.length+1).padStart(3,'0'),title:c.title||'Comunicado sin título',type:'Comunicado',owner:'Comunicación',date:c.date,status:'Pendiente',person:c.contactName,area:c.area,brief:c.information,format:'Comunicado · '+c.language,comments:'',reason:'',evidence:'',communication:c};requests.push(r);$('#commForm').hidden=true;$('.steps').hidden=true;$('#commSuccess').hidden=false;$('#commSuccessFolio').textContent=r.id+' · '+r.title;render();toast('Solicitud agregada a la demo de esta visita.');};
$('#anotherComm').onclick=()=>{$('#commForm').reset();$('#commForm').hidden=false;$('.steps').hidden=false;$('#commSuccess').hidden=true;$('#otherAudienceLabel').hidden=true;$('#otherAudience').required=false;$('#audienceError').hidden=true;$('#commForm').querySelectorAll('input,select,textarea').forEach(f=>f.setCustomValidity(''));commCapacity();showCommStep(0);};
showCommStep(0);
