(() => {
  const root=document.querySelector('#campana');
  const recruitment=document.createElement('div');
  while(root.firstChild)recruitment.append(root.firstChild);
  const menu=document.createElement('div'),brief=document.createElement('div');
  menu.innerHTML='<div class="section-head"><div><p class="eyebrow">CAMPAÑAS Y PROYECTOS</p><h1>¿Qué campaña necesitas?</h1><p>Prepara el brief para que Marketing pueda evaluar y planear el proyecto.</p></div></div><div class="design-service-grid"><button type="button" data-campaign="brief"><span class="eyebrow">01</span><strong>Campaña o proyecto de Marketing</strong><span>Campañas comerciales e internas: público, objetivos, canales, entregables y presupuesto.</span></button><button type="button" data-campaign="recruitment"><span class="eyebrow">02</span><strong>Campaña de reclutamiento</strong><span>Vacantes, clientes, cobertura y condiciones de contratación.</span></button></div>';
  root.append(menu,recruitment,brief);recruitment.hidden=true;brief.hidden=true;
  const back=document.createElement('button');back.type='button';back.className='back-link';back.textContent='Cambiar tipo de campaña';recruitment.prepend(back);
  function home(){menu.hidden=false;recruitment.hidden=true;brief.hidden=true;menu.querySelector('h1').tabIndex=-1;menu.querySelector('h1').focus();}
  back.onclick=home;
  const f=(key,label,type='text',options=[],required=true,help='',when=null)=>({key,label,type,options,required,help,when});
  const sections=[
    ['Datos generales',[
      f('area','Área solicitante','select',designAreas),f('otherArea','Especifica tu área','text',[],true,'',d=>d.area==='Otro'),f('person','Responsable del proyecto'),f('title','Nombre de campaña o proyecto'),f('campaignType','Tipo de campaña','select',['Comercial','Interna']),f('date','Fecha deseada de inicio del proyecto','date'),f('end','Fecha deseada de término del proyecto','date')]],
    ['Sobre el proyecto',[
      f('description','Cuéntanos sobre tu proyecto','textarea',[],true,'Mínimo 30 palabras. Describe la necesidad, el contexto y el resultado esperado.'),f('audience','Público al que se dirige','checks',['IC México','IC Admin','Embajada EUA','Guardias','Clientes','Prospectos','Proveedores','Otros'],true,'Selecciona todas las opciones que correspondan.'),f('otherAudience','Especifica el otro público','text',[],true,'',d=>d.audience?.includes('Otros')),f('objective','¿Qué queremos que haga, piense o conozca el público?','textarea'),f('zone','Zona donde se llevará a cabo','select',['Nacional','Regional','Interna','Externa','Otro']),f('otherZone','Especifica la zona','text',[],true,'',d=>['Regional','Otro'].includes(d.zone))]],
    ['Materiales disponibles',[
      f('informationMode','¿Cómo compartirás el texto o la información?','select',['Escribir aquí','Adjuntar archivo']),f('information','Texto o información para la campaña','textarea',[],true,'Incluye el contenido que debe utilizarse.',d=>d.informationMode==='Escribir aquí'),f('informationFile','Archivo de texto o información','file',[],true,'PDF o archivo de texto. En esta demo se conserva solo el nombre.',d=>d.informationMode==='Adjuntar archivo'),f('hasLogos','Cuento con logotipos','checkbox',[],false),f('logos','Logotipos disponibles','file',[],true,'Selecciona los archivos del logotipo.',d=>d.hasLogos),f('hasSlogan','Cuento con un slogan','checkbox',[],false),f('slogan','Slogan de la campaña','text',[],true,'',d=>d.hasSlogan),f('hasPhotos','Cuento con fotografías para la campaña','checkbox',[],false),f('photos','Fotografías disponibles','file',[],true,'Selecciona las fotografías que se usarán.',d=>d.hasPhotos),f('termsMode','¿Cómo compartirás los lineamientos o términos y condiciones?','select',['Escribir aquí','Adjuntar archivo']),f('terms','Lineamientos o términos y condiciones','textarea',[],true,'Si no aplican, indícalo expresamente para revisión de Marketing.',d=>d.termsMode==='Escribir aquí'),f('termsFile','Archivo de lineamientos o términos y condiciones','file',[],true,'Selecciona el documento con los lineamientos.',d=>d.termsMode==='Adjuntar archivo'),f('additional','Documento adicional para la campaña','file',[],false,'Opcional. Información de apoyo para el proyecto.')]],
    ['Difusión y entregables',[
      f('channels','Medios de difusión que consideras para tu campaña','checks',['Mailing','Meta','Google','LinkedIn','TikTok','WhatsApp','Instagram','Facebook','Redes sociales orgánicas (sin pago)','Redes sociales pagadas','Sitio Web','Gaceta','Material impreso','Otro'],true,'Puedes elegir varios. Marketing revisará la propuesta de canales.'),f('otherChannel','Especifica el otro medio de difusión','text',[],true,'',d=>d.channels?.includes('Otro')),
      f('digital','Materiales gráficos digitales','checks',['Post','Video','Historia en redes sociales','Fotografías','Logotipo','Presentación','Carrusel','Otro'],false,'Selecciona los entregables digitales que necesitas.'),f('otherDigital','Especifica el otro material digital','text',[],true,'',d=>d.digital?.includes('Otro')),
      f('printed','Materiales gráficos impresos','checks',['Prototipado','Banner','Lona','Flyer','Tríptico','Libreta','Pluma','Pin','Bolsa','Credencial','Hoja membretada','Gorra','Vaso','Playera','Otro'],false,'Selecciona los entregables impresos que necesitas.'),f('otherPrinted','Especifica el otro material impreso','text',[],true,'',d=>d.printed?.includes('Otro'))]],
    ['Presupuesto y llamada',[
      f('budget','¿La campaña cuenta con presupuesto?','select',['Sí','No','Pendiente']),f('amount','Monto disponible que se considera','text',[],true,'Indica el monto y la moneda.',d=>d.budget==='Sí'),f('supplier','¿Requiere proveedor o cotización?','select',['Sí','No']),f('paid','¿Requiere gasto publicitario?','select',['Sí','No']),f('extraCosts','Algún gasto extra para considerar','textarea',[],false),f('call','Quiero proponer una fecha de llamada','checkbox',[],false,'Marketing confirmará la disponibilidad; esta selección no reserva una reunión.'),f('callDate','Fecha propuesta para la llamada','date',[],true,'',d=>d.call),f('callTime','Hora propuesta para la llamada','time',[],false,'Horario de Ciudad de México.',d=>d.call)]]
  ];
  function openBrief(){menu.hidden=true;recruitment.hidden=true;brief.hidden=false;let step=0;const data={};const fields=sections.flatMap(s=>s[1]);
    brief.innerHTML='<button type="button" class="back-link" data-home>Cambiar tipo de campaña</button><div class="section-head"><div><p class="eyebrow">MARKETING</p><h1>Brief de campaña o proyecto</h1><p>Comparte la información para evaluar, planear y dar seguimiento a la campaña.</p></div></div><div class="demo-banner"><strong>Captura de prueba</strong><span>Los datos duran durante esta visita. No se envían archivos, notificaciones ni invitaciones.</span></div><div class="comm-layout"><div class="comm-main"><ol class="steps brief-steps">'+[...sections.map(s=>s[0]),'Revisión'].map((label,i)=>'<li data-brief-label="'+i+'"><span>'+(i+1)+'</span>'+label+'</li>').join('')+'</ol><form novalidate>'+sections.map(([label,fs],i)=>'<fieldset data-brief-step="'+i+'"><legend>'+label+'</legend>'+fs.map(f=>controlHTML(f,'brief')).join('')+(i===0?'<p class="field-help"><strong>Prioridad: pendiente de valoración por Marketing.</strong></p>':'')+'</fieldset>').join('')+'<fieldset data-brief-step="5"><legend>Revisa el brief completo</legend><div data-review></div></fieldset><div class="comm-actions"><button type="button" data-prev>Anterior</button><span data-progress></span><button type="button" class="primary" data-next>Continuar</button><button type="submit" class="primary" data-save hidden>Guardar brief demo</button></div></form><div data-success hidden><h2>Gracias por compartir tu proyecto.</h2><p>El siguiente paso es que una persona de Marketing se contacte contigo para revisar el brief.</p><p data-folio></p><p>Este registro es de prueba. No se ha enviado al equipo ni reservado una llamada; se restablece al recargar.</p><button type="button" data-home>Crear otra solicitud</button></div></div><aside class="comm-aside"><p class="eyebrow">ANTES DE SOLICITAR</p><h2>Un objetivo claro orienta la campaña.</h2><p>Define el público, el mensaje y los entregables. Marketing revisará la prioridad, los canales, el presupuesto y las fechas.</p><p>La llamada se registra como fecha propuesta y requiere confirmación del equipo.</p></aside></div>';
    const form=brief.querySelector('form');
    for(const f of fields.filter(f=>f.type==='checks'&&!f.required))form.querySelector('[data-field="'+f.key+'"] .field-label').textContent=f.label+' (opcional)';
    form.querySelectorAll('[data-check-error]').forEach(e=>{e.textContent='Selecciona al menos una opción.';});
    for(const key of ['informationFile','termsFile','additional'])form.elements[key].accept='.pdf,.txt,.doc,.docx,.rtf';
    form.elements.logos.accept='.png,.jpg,.jpeg,.webp,.svg,.pdf,.ai,.eps';form.elements.photos.accept='image/jpeg,image/png,image/webp';
    const counter=document.createElement('span');counter.className='field-help';counter.setAttribute('aria-live','polite');form.elements.description.after(counter);
    function capture(){for(const f of fields){const els=[...form.querySelectorAll('[name="'+f.key+'"]')];data[f.key]=f.type==='checks'?els.filter(e=>e.checked).map(e=>e.value):f.type==='checkbox'?els[0].checked:f.type==='file'?[...els[0].files].map(x=>({name:x.name,size:x.size})):els[0].value.trim();}return data;}
    const visible=f=>!f.when||f.when(data);const wordCount=()=>data.description?.match(/[\p{L}\p{N}]+(?:['’\-][\p{L}\p{N}]+)*/gu)?.length||0;
    function sync(){capture();for(const f of fields){const wrap=form.querySelector('[data-field="'+f.key+'"]');wrap.hidden=!visible(f);wrap.querySelectorAll('input,textarea,select').forEach(e=>e.disabled=!visible(f)||Number(wrap.closest('fieldset').dataset.briefStep)!==step);}counter.textContent=wordCount()+' de 30 palabras mínimas';}
    function pairs(){capture();return [['Tipo de solicitud','Campaña o proyecto de Marketing'],['Nivel de prioridad','Pendiente de valoración por Marketing'],...fields.filter(visible).map(f=>[f.label,f.type==='checkbox'?(data[f.key]?'Sí':'No'):f.type==='file'?data[f.key].map(x=>x.name):data[f.key]])];}
    function show(n){step=n;form.querySelectorAll('fieldset').forEach((e,i)=>e.hidden=i!==n);sync();brief.querySelectorAll('[data-brief-label]').forEach((e,i)=>{e.classList.toggle('current',i===n);if(i===n)e.setAttribute('aria-current','step');else e.removeAttribute('aria-current');});brief.querySelector('[data-prev]').hidden=n===0;brief.querySelector('[data-next]').hidden=n===5;brief.querySelector('[data-save]').hidden=n!==5;brief.querySelector('[data-progress]').textContent='Paso '+(n+1)+' de 6';if(n===5)brief.querySelector('[data-review]').innerHTML=pairsHTML(pairs());const l=form.querySelector('[data-brief-step="'+n+'"] legend');l.tabIndex=-1;l.focus();}
    function fail(el,msg){el.setCustomValidity(msg);el.reportValidity();return false;}
    function validate(){sync();for(const f of sections[step]?.[1]||[]){if(!visible(f))continue;const el=form.querySelector('[name="'+f.key+'"]');el.setCustomValidity('');if(f.type==='checks'){const ok=!f.required||data[f.key].length>0;form.querySelector('[data-field="'+f.key+'"] [data-check-error]').hidden=ok;if(!ok)return fail(el,'Selecciona al menos una opción.');}else if(f.type==='file'){if(f.required&&!el.files.length)return fail(el,'Selecciona al menos un archivo.');const patterns={informationFile:/\.(pdf|txt|docx?|rtf)$/i,termsFile:/\.(pdf|txt|docx?|rtf)$/i,additional:/\.(pdf|txt|docx?|rtf)$/i,logos:/\.(png|jpe?g|webp|svg|pdf|ai|eps)$/i,photos:/\.(png|jpe?g|webp)$/i};if([...el.files].some(file=>!patterns[f.key].test(file.name)))return fail(el,'Selecciona un archivo del formato indicado.');}else if(f.required&&!data[f.key])return fail(el,'Completa este campo.');if(!el.reportValidity())return false;}
      if(step===0&&data.end<data.date)return fail(form.elements.end,'La fecha de término debe ser igual o posterior al inicio.');
      if(step===1&&wordCount()<30)return fail(form.elements.description,'Describe tu proyecto en al menos 30 palabras.');
      if(step===4&&data.call&&data.callDate<today)return fail(form.elements.callDate,'Elige una fecha a partir de hoy.');return true;}
    form.addEventListener('input',e=>{e.target.setCustomValidity?.('');sync();});form.addEventListener('change',e=>{e.target.setCustomValidity?.('');sync();});
    brief.querySelector('[data-next]').onclick=()=>{if(validate())show(step+1);};brief.querySelector('[data-prev]').onclick=()=>show(step-1);
    form.onsubmit=e=>{e.preventDefault();if(step!==5){if(validate())show(step+1);return;}const answers=pairs();const r={id:'MKT-DEMO-'+String(requests.length+1).padStart(3,'0'),title:data.title,type:'Campaña',owner:'Marketing',date:data.date,status:'Pendiente',person:data.person,area:data.area==='Otro'?data.otherArea:data.area,brief:data.description,format:'Campaña '+data.campaignType.toLowerCase(),comments:'',reason:'',evidence:'',answers,priority:'Pendiente de valoración',campaignBrief:true};addDemoRequest(r);form.hidden=true;brief.querySelector('.steps').hidden=true;brief.querySelector('[data-success]').hidden=false;brief.querySelector('[data-folio]').textContent=r.id+' · '+r.title;render();};
    brief.querySelectorAll('[data-home]').forEach(b=>b.onclick=home);show(0);
  }
  menu.querySelector('[data-campaign="brief"]').onclick=openBrief;
  menu.querySelector('[data-campaign="recruitment"]').onclick=()=>{menu.hidden=true;brief.hidden=true;recruitment.hidden=false;};
  // Priority belongs to Marketing and does not change the requester's original answers.
  const label=document.createElement('label');label.textContent='Prioridad valorada por Marketing';const priority=document.createElement('select');priority.id='editCampaignPriority';label.htmlFor=priority.id;priority.innerHTML=['Pendiente de valoración','Baja','Media','Alta','Urgente'].map(x=>'<option>'+x+'</option>').join('');label.append(priority);label.hidden=true;document.querySelector('#editStatus').closest('.edit-grid').after(label);
  const previousOpen=openDetail;openDetail=function(id){previousOpen(id);const r=scoped().find(x=>x.id===id);label.hidden=!r?.campaignBrief;if(r?.campaignBrief){priority.value=r.priority||'Pendiente de valoración';priority.disabled=!isAdmin();}};
  const previousSave=document.querySelector('#editForm').onsubmit;document.querySelector('#editForm').onsubmit=function(e){const r=scoped().find(x=>x.id===selected);const next=priority.value;previousSave.call(this,e);if(r?.campaignBrief&&isAdmin()&&!document.querySelector('#detail').open&&r.priority!==next){r.priority=next;(r.history??=[]).push({actor:currentUser().name,text:'Prioridad de Marketing: '+next,date:new Date().toLocaleString('es-MX')+' · demo'});render();toast('Seguimiento guardado en la demo.');}};
  // Update the existing service entry to include the broader campaign brief.
  const card=document.querySelector('#formCards [data-view="campana"]')?.closest('article');if(card){card.querySelector('h2').textContent='Campañas y proyectos';card.querySelector('p').textContent='Prepara una campaña comercial, interna o de reclutamiento.';card.querySelector('button').textContent='Crear campaña o proyecto';}
})();
