(() => {
  const root = document.querySelector('#diseno');
  const existing = document.createElement('div');
  existing.className = 'design-material-form';
  while (root.firstChild) existing.append(root.firstChild);
  const hub = document.createElement('div');
  hub.className = 'design-process-hub';
  hub.innerHTML = '<div class="section-head"><div><p class="eyebrow">ESTUDIO DE DISEÑO</p><h1>¿Qué necesitas crear?</h1><p>Elige el servicio para preparar tu solicitud.</p></div></div><div class="design-service-grid">'+[
    ['material','Diseño de materiales','Piezas digitales e impresas, formatos, medidas y contenido.'],
    ['photo','Fotografía corporativa','Agenda una sesión en CDMX o envía tu fotografía regional.'],
    ['coverage','Levantamiento de imagen','Solicita cobertura de fotografía o video para un evento.'],
    ['prototype','Prototipado','Solicita aplicaciones de un diseño en artículos promocionales.']
  ].map(([id,title,desc],i)=>'<button type="button" data-design-service="'+id+'"><span class="eyebrow">0'+(i+1)+'</span><strong>'+title+'</strong><span>'+desc+'</span></button>').join('')+'</div>';
  const process = document.createElement('div');
  root.append(hub,existing,process);
  existing.hidden=true; process.hidden=true;
  const materialBack=document.createElement('button');materialBack.type='button';materialBack.className='back-link';materialBack.textContent='Cambiar tipo de solicitud';existing.prepend(materialBack);
  function home(){existing.hidden=true;process.hidden=true;hub.hidden=false;hub.querySelector('h1').tabIndex=-1;hub.querySelector('h1').focus();}
  materialBack.onclick=home;
  const companies=['Inter-Con México','IC Admin','Embajada de EUA'];
  const cf=(key,label,type='text',options=[],required=true,help='',when=null)=>({key,label,type,options,required,help,when});
  const requester=[cf('person','Responsable de la solicitud'),cf('area','Área solicitante','select',designAreas),cf('otherArea','Especifica tu área','text',[],true,'',d=>d.area==='Otro')];
  const slots=[];for(let hour of [9,10,16])for(let min=0;min<60;min+=10)slots.push(String(hour).padStart(2,'0')+':'+String(min).padStart(2,'0'));
  const configs={
    photo:{title:'Fotografía corporativa',labels:['Datos generales','Fotografía'],steps:[
      [cf('person','Nombre completo'),cf('company','Empresa','select',companies),cf('location','¿Dónde te encuentras?','select',['Local – Oficinas CDMX','Regional'])],
      [cf('date','Día de la sesión','date',[],true,'Lunes y jueves. Horarios de CDMX: 9:00 a 11:00 y 16:00 a 17:00. Citas de 10 minutos.',d=>d.location==='Local – Oficinas CDMX'),cf('slot','Hora de la sesión','select',slots,true,'Selecciona el inicio de tu cita.',d=>d.location==='Local – Oficinas CDMX'),cf('photo','Tu fotografía corporativa','file',[],true,'Selecciona una imagen. La demo conserva su nombre; no la envía a Marketing.',d=>d.location==='Regional')]],
      aside:'La sesión local se agenda en intervalos de 10 minutos. Las fotografías regionales se revisarán antes de utilizarse.',
      guide:'La infografía de preparación local y la guía de requisitos regionales están pendientes de recibir de Marketing.'},
    coverage:{title:'Levantamiento de imagen',labels:['Solicitud','Evento y cobertura'],steps:[requester.concat([cf('title','Nombre del evento o actividad')]),
      [cf('date','Fecha del levantamiento','date'),cf('schedule','¿Ya conoces el horario del evento?','select',['Sí, ya está confirmado.','Aún está por confirmar.']),cf('start','Hora de inicio','time',[],true,'',d=>d.schedule==='Sí, ya está confirmado.'),cf('end','Hora de término','time',[],true,'',d=>d.schedule==='Sí, ya está confirmado.'),cf('place','Lugar del evento'),cf('coverage','Tipo de cobertura requerida','checks',['Fotografía','Video'],true,'Puedes elegir una o ambas opciones.'),cf('meeting','¿Requieres una reunión previa con Marketing?','select',['Sí, requiero una reunión previa.','No, la información proporcionada es suficiente.'],true,'Indica si necesitas explicar requerimientos específicos antes del evento.')]],aside:'Comparte fecha, ubicación y cobertura. Si el horario no está confirmado, quedará registrado como pendiente.'},
    prototype:{title:'Prototipado',labels:['Solicitud','Aplicaciones y referencias'],steps:[requester.concat([cf('date','Fecha de entrega deseada','date',[],true,'Marketing confirmará el plazo según el alcance.')]),
      [cf('quantity','¿Cuántos prototipos requieres?','number',[],true,'Número de aplicaciones diferentes del mismo diseño.'),cf('articles','¿Qué tipo de prototipo requieres?','textarea',[],true,'Por ejemplo: pluma, libreta, pin, termo o playera.'),cf('logos','¿Qué logotipo debe llevar?','checks',['IC','Inter-Con','IC Admin','Logotipo de un área','Se requiere un logotipo nuevo','Otro'],true,'Puedes seleccionar más de uno.'),cf('areaLogo','Nombre del área del logotipo','text',[],true,'',d=>d.logos?.includes('Logotipo de un área')),cf('otherLogo','Especifica el otro logotipo','text',[],true,'',d=>d.logos?.includes('Otro')),cf('extra','¿Se agregará algún texto, imagen o elemento adicional al diseño?','select',['Sí','No']),cf('elements','Texto, imagen o elemento adicional','textarea',[],true,'',d=>d.extra==='Sí')]],aside:'Cada prototipo requiere una imagen de referencia. Separa los artículos y sus referencias para que el equipo pueda identificar cada aplicación.'}
  };
  function renderProcess(kind){
    const config=configs[kind];let step=0;const data={};
    hub.hidden=true;existing.hidden=true;process.hidden=false;
    process.innerHTML='<button type="button" class="back-link" data-hub>Cambiar tipo de solicitud</button><div class="section-head"><div><p class="eyebrow">DISEÑO</p><h1>'+config.title+'</h1></div></div><div class="demo-banner"><strong>Captura de prueba</strong><span>Datos de ejemplo durante esta visita. No se reservan citas reales ni se envían archivos.</span></div><div class="comm-layout"><div class="comm-main"><ol class="steps">'+[...config.labels,'Revisión'].map((l,i)=>'<li data-label="'+i+'"><span>'+(i+1)+'</span>'+l+'</li>').join('')+'</ol><form novalidate>'+config.steps.map((fields,i)=>'<fieldset data-process-step="'+i+'"><legend>'+config.labels[i]+'</legend>'+fields.map(f=>controlHTML(f,'design-'+kind)).join('')+(kind==='prototype'&&i===1?'<div data-references></div>':'')+'</fieldset>').join('')+'<fieldset data-process-step="2"><legend>Revisa tu solicitud</legend><div data-review></div></fieldset><div class="comm-actions"><button type="button" data-prev>Anterior</button><span data-progress></span><button type="button" class="primary" data-next>Continuar</button><button type="submit" class="primary" data-save hidden>Guardar solicitud demo</button></div></form><div data-success hidden><h2>Solicitud registrada en la demo</h2><p data-result></p><p data-folio></p><p>Se restablece al recargar. No se han enviado datos ni archivos a Marketing.</p><button type="button" data-hub>Crear otra solicitud</button></div></div><aside class="comm-aside"><p class="eyebrow">ANTES DE SOLICITAR</p><p>'+config.aside+'</p>'+(config.guide?'<p class="guide-pending">'+config.guide+'</p>':'')+'</aside></div>';
    const form=process.querySelector('form'),fields=config.steps.flat();
    form.querySelectorAll('input[type="file"]').forEach(e=>{e.multiple=false;e.accept='image/jpeg,image/png,image/webp';});
    function capture(){for(const f of fields){const els=[...form.querySelectorAll('[name="'+f.key+'"]')];data[f.key]=f.type==='checks'?els.filter(e=>e.checked).map(e=>e.value):f.type==='file'?[...els[0].files].map(x=>x.name):els[0].value.trim();}return data;}
    const visible=f=>!f.when||f.when(data);
    function sync(){capture();for(const f of fields){const wrap=form.querySelector('[data-field="'+f.key+'"]');wrap.hidden=!visible(f);wrap.querySelectorAll('input,select,textarea').forEach(e=>e.disabled=!visible(f)||Number(wrap.closest('fieldset').dataset.processStep)!==step);}
      if(kind==='prototype'){const holder=form.querySelector('[data-references]');const n=Number(data.quantity),valid=Number.isSafeInteger(n)&&n>0;const desired=valid?n:0;const current=holder.querySelectorAll('[data-reference]');for(let i=current.length;i<desired;i++){const label=document.createElement('label');label.dataset.reference=String(i);label.innerHTML='Referencia del prototipo '+(i+1)+' <b>*</b><input type="file" name="reference'+i+'" accept="image/jpeg,image/png,image/webp" required><span class="field-help">Una imagen para esta aplicación. En la demo se conserva solo el nombre.</span>';holder.append(label);}for(let i=current.length-1;i>=desired;i--)current[i].remove();holder.querySelectorAll('input').forEach(e=>e.disabled=step!==1);}
    }
    function pairs(){capture();const p=[['Tipo de solicitud',config.title],...fields.filter(visible).map(f=>[f.label,data[f.key]])];if(kind==='prototype')form.querySelectorAll('[data-reference] input').forEach((e,i)=>p.push(['Referencia del prototipo '+(i+1),e.files[0]?.name||'Sin archivo']));return p;}
    function show(n){step=n;form.querySelectorAll('fieldset').forEach((e,i)=>e.hidden=i!==n);sync();process.querySelectorAll('[data-label]').forEach((e,i)=>{e.classList.toggle('current',i===n);if(i===n)e.setAttribute('aria-current','step');else e.removeAttribute('aria-current');});process.querySelector('[data-prev]').hidden=n===0;process.querySelector('[data-next]').hidden=n===2;process.querySelector('[data-save]').hidden=n!==2;process.querySelector('[data-progress]').textContent='Paso '+(n+1)+' de 3';if(n===2)process.querySelector('[data-review]').innerHTML=pairsHTML(pairs());const l=form.querySelector('[data-process-step="'+n+'"] legend');l.tabIndex=-1;l.focus();}
    const imageValid=file=>file&&['image/jpeg','image/png','image/webp'].includes(file.type);
    function error(el,message){el.setCustomValidity(message);el.reportValidity();return false;}
    function validate(){sync();for(const f of config.steps[step]||[]){if(!visible(f))continue;const el=form.querySelector('[name="'+f.key+'"]');el.setCustomValidity('');if(f.type==='checks'){const ok=data[f.key].length>0;const msg=form.querySelector('[data-field="'+f.key+'"] [data-check-error]');msg.textContent='Selecciona al menos una opción.';msg.hidden=ok;if(!ok)return error(el,'Selecciona al menos una opción.');}else if(f.type==='file'){if(!imageValid(el.files[0]))return error(el,'Selecciona una imagen JPG, PNG o WebP.');}else if(f.required&&!data[f.key])return error(el,'Completa este campo.');if(f.type==='number'&&(!Number.isSafeInteger(Number(data[f.key]))||Number(data[f.key])<1))return error(el,'Indica una cantidad entera mayor a cero.');if(!el.reportValidity())return false;}
      if(step===1&&kind==='photo'&&data.location==='Local – Oficinas CDMX'){const day=new Date(data.date+'T12:00:00').getDay();if(data.date<today||![1,4].includes(day))return error(form.elements.date,'Elige un lunes o jueves a partir de hoy.');const busy=requests.some(r=>r.format==='Fotografía corporativa'&&r.date===data.date&&r.status!=='Rechazado'&&r.answers?.some(([key,value])=>key==='Hora de la sesión'&&value===data.slot));if(busy)return error(form.elements.slot,'Esta cita ya está ocupada en la demo. Selecciona otro horario.');}
      if(step===1&&kind==='coverage'&&data.schedule==='Sí, ya está confirmado.'&&data.end<=data.start)return error(form.elements.end,'La hora de término debe ser posterior al inicio.');
      if(step===1&&kind==='prototype')for(const el of form.querySelectorAll('[data-reference] input')){el.setCustomValidity('');if(!imageValid(el.files[0]))return error(el,'Adjunta una imagen JPG, PNG o WebP por cada prototipo.');}
      return true;
    }
    form.addEventListener('input',e=>{e.target.setCustomValidity?.('');sync();});form.addEventListener('change',e=>{e.target.setCustomValidity?.('');sync();});
    process.querySelector('[data-next]').onclick=()=>{if(validate())show(step+1);};process.querySelector('[data-prev]').onclick=()=>show(step-1);
    form.onsubmit=e=>{e.preventDefault();if(step!==2){if(validate())show(step+1);return;}const saved=pairs();const r={id:'MKT-DEMO-'+String(requests.length+1).padStart(3,'0'),title:kind==='photo'?'Fotografía corporativa · '+data.person:kind==='coverage'?data.title:'Prototipado · '+data.articles,type:'Diseño',owner:'Diseño',date:data.date||today,status:'Pendiente',person:data.person,area:(data.area==='Otro'?data.otherArea:data.area)||data.company,brief:kind==='coverage'?'Cobertura de '+data.coverage.join(' y ')+' en '+data.place+'. '+data.meeting:kind==='photo'?data.location==='Regional'?'Revisar la fotografía corporativa enviada.':'Sesión local de fotografía corporativa a las '+data.slot+'.':'Preparar '+data.quantity+' aplicaciones: '+data.articles,format:config.title,comments:'',reason:'',evidence:'',answers:saved};addDemoRequest(r);form.hidden=true;process.querySelector('.steps').hidden=true;process.querySelector('[data-success]').hidden=false;process.querySelector('[data-folio]').textContent=r.id+' · '+r.title;process.querySelector('[data-result]').textContent=kind==='photo'?data.location==='Regional'?'Fotografía registrada en la demo para revisión.':'Cita registrada en la demo para el '+dateText(data.date)+' a las '+data.slot+'.':'La solicitud aparece en la bandeja, pendiente de asignación por Nydia.';render();};
    process.querySelectorAll('[data-hub]').forEach(b=>b.onclick=home);show(0);
  }
  hub.querySelectorAll('[data-design-service]').forEach(b=>b.onclick=()=>{if(b.dataset.designService==='material'){hub.hidden=true;existing.hidden=false;process.hidden=true;}else renderProcess(b.dataset.designService);});
})();
